### ISSUE TITLE
Production files

### ISSUE THREAD

**Issue by CountParadox** [JGAguado/Smart_Powermeter#7]
Hi OP

Thanks for the hard work, your board looks amazing :) 

Would it be possible to get some production files eg. gerbers, drill, bom, placement etc to get some board s manufactured at JLCPCB or PCBway for example ? 

Your store is out of stock and theres no clues when they may be back :( 

Myself and a few friends would love to get a few boards

I would appreciate any help ! 

Thank you

**Comment by JGAguado** [comment]
Hi Lewis,

Thanks for your interest and support! Normally I don't upload the production files, but the design ones, so you can freely generate your production file. 

Since I am still testing the V2R1, I haven't tagged a release, I hope to validate the functionalities this next week and update the documentation, but the design files already available wouldn't change.

If you are more interested in acquiring some semi-assembled units (I have some prototypes V1R1 and V1R2), send me an email to jon-garcia@hotmail.com
