### ISSUE TITLE
ADC measurement resolution

### ISSUE THREAD

**Issue by jibrilsharafi** [JGAguado/Smart_Powermeter#9]
Hi, 

I see that the board has no external ADC or energy metering IC, which means all the (current) waveform sampling will be done on the ESP32. Isn't this non-recommended since the ADC has a lot of noise, especially in the mV region (which translates into 100s of mA and 10s of W)?

Have you taken this into account in your board design?

**Comment by JGAguado** [comment]
Hi @jibrilsharafi ,

Yes, you are right, The reading is done through the internal ESP32's ADC. 

This doesn't necessarily mean that has a lot of noise, since it has a 12-bit resolution and the RMS can be read in a range of 1.65V, we get a resolution of 0.402mV. Depending on the CT clamp ratio you choose, you will be able to read the current with more or less quality.
On the other hand, by using ESPHome, the [CT Clamp component](https://esphome.io/components/sensor/ct_clamp.html) computes the RMS directly, so this helps filtering undesired noise (I think around 900 samples/second).
I'm aware it's not a completely noise-proof design, but so far does a good job at a reasonable cost: for monitoring, in a non-invasive way, my home's apparent power is more than enough.

Best regards!
